variable "ami" {}
variable "instance_type" {}
variable "ec2_tags" {}
variable "availability_zone" {}
variable "monitoring" {}
variable "subnet_id" {}
variable "key_name" {}
variable "sg_ids" {}
variable "rbd_size" {}
variable "rbd_type" {}
variable "iam_instance_profile" {}